language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.1

env:
  - MAGENTO_VERSION=magento-mirror-1.9.2.4
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.8.0.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2

before_script:
  - phpenv config-rm xdebug.ini
  - composer global require n98/magerun
  - composer global require colinmollenhour/modman
  - export PATH=$PATH:$HOME/.composer/vendor/bin

script:
  - bash app/code/community/TIG/PostNL/Test/setup.sh

cache:
  directories:
  - $HOME/tools
  - $HOME/.composer/cache