language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

allow_failures:
  - 7.1

env:
  - MAGENTO_VERSION=magento-mirror-1.9.2.4
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.8.0.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2

script:
  - bash app/code/community/TIG/PostNL/Test/setup.sh