language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - TESTSUITE=unit
    - CODE_COVERAGE=false
    - TEST_RUNNER_OPTIONS=""

  matrix:
    - MAGENTO_VERSION=magento-mirror-1.9.3.10

matrix:
  include:
  - php: 7.1
    env: MAGENTO_VERSION=magento-mirror-1.9.3.10 ENABLE_FLAT_CATALOG=true
  - php: 7.0
    env: MAGENTO_VERSION=magento-mirror-1.9.3.10 CODE_COVERAGE=true
  - php: 7.0
    env: MAGENTO_VERSION=magento-mirror-1.9.2.4
  - php: 7.0
    env: MAGENTO_VERSION=magento-mirror-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=magento-mirror-1.8.0.0

  fast_finish: true

  allow_failures:
  - php: nightly

before_script:
  - composer config -a -g http-basic.repo.magento.com $COMPOSER_MAGENTO_USERNAME $COMPOSER_MAGENTO_PASSWORD
  - if [ "${CODE_COVERAGE}" = "false" ]; then phpenv config-rm xdebug.ini; fi
  - if [ "${CODE_COVERAGE}" = "true" ]; then TEST_RUNNER_OPTIONS="${TEST_RUNNER_OPTIONS} --coverage-clover build/logs/clover.xml"; fi
  - if find . -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n 1 -P 8 php -l | grep -v "No syntax errors detected"; then exit 1; fi
  - export PATH=$PATH:$HOME/.composer/vendor/bin
  - bash app/code/community/TIG/PostNL/Test/Scripts/InstallDependencies.sh
  - bash app/code/community/TIG/PostNL/Test/Scripts/Setup.sh

script:
  - vendor/bin/phpcs --runtime-set installed_paths vendor/magento/marketplace-eqp -p --standard=MEQP1 --severity=10 --ignore=*/vendor/*,*/app/code/community/TIG/PostNL/Test/*,*/app/code/community/TIG/PostNL/docs/*,*/app/code/community/TIG/PostNL/Model/ExtensionControl/Webservices.php .
  - $HOME/.composer/vendor/bin/phpunit -c "/tmp/magento/public/app/code/community/TIG/PostNL/Test/phpunit.xml" --testsuite=$TESTSUITE ${TEST_RUNNER_OPTIONS}

cache:
  directories:
  - $HOME/.composer

after_success:
  - bash app/code/community/TIG/PostNL/Test/Scripts/AfterSuccess.sh
